version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 5
  method-complexity:
    enabled: true
    config:
      threshold: 15
  return-statements:
    enabled: true
    config:
      threshold: 10
