require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable
  SuggestExtensions: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/EmptyLineBetweenDefs:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/SpaceAfterComma:
  Enabled: true

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: true

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeSemicolon:
  Enabled: true


Lint/MissingSuper:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true


Metrics/AbcSize:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

# Offense count: 13
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes.
# URISchemes: http, https
Layout/LineLength:
  Max: 80

Metrics/MethodLength:
  Enabled: false

# Offense count: 1
Metrics/PerceivedComplexity:
  Max: 8


Performance/RedundantBlockCall:
  Enabled: true


Naming/MethodName:
  Enabled: true

Naming/BinaryOperatorParameterName:
  Enabled: true


Style/ClassVars:
  Enabled: true

Style/Documentation:
  Enabled: true

Style/DoubleNegation:
  Enabled: true

Style/EmptyLiteral:
  Enabled: true

Style/GuardClause:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/NumericLiterals:
  MinDigits: 5

Style/PreferredHashMethods:
  Enabled: true

Style/RedundantArgument:
  Enabled: false

Style/RedundantFetchBlock:
  Enabled: false

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/SafeNavigation:
  Enabled: false

Style/SingleLineMethods:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names

Style/StringLiterals:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/RedundantPercentQ:
  Enabled: true

Style/DateTime:
  Enabled: false
